Fix `--version` for non-development builds (#271)
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/make_bundle_conda.yml b/.github/workflows/make_bundle_conda.yml
--- a/.github/workflows/make_bundle_conda.yml
+++ b/.github/workflows/make_bundle_conda.yml
@@ -117,7 +117,7 @@ jobs:
           CONSTRUCTOR_USE_LOCAL: 1
         run: |
           set -x
-          pip install -e . --no-deps -vvv
+          pip install -e . --no-deps
           echo "NAPARI_VERSION=$(python ../napari-packaging/build_installers.py --version)" >> $GITHUB_ENV
           echo "NAPARI_ARCH=$(python ../napari-packaging/build_installers.py --arch)" >> $GITHUB_ENV
 
@@ -129,6 +129,11 @@ jobs:
           # rm recipe from conda-forge's feedstock and replace with our napari/packaging version
           rm -rf recipe/
           cp -r ../napari-packaging/conda-recipe recipe
+
+          if [[ -z "${NAPARI_VERSION}" ]]; then
+            echo "Could not estimate napari version in previous step. Debug."
+            exit 1
+          fi
 
           sed -i -e "s|^  version: \".*\"|  version: \"${NAPARI_VERSION}\"|" \
                  -e "s|^  build_number: [0-9]+|  build_number: 0|" \
